const listGift = [
    {
        id: 1,
        name: 'Granola siêu hạt ăn kiêng 15% yến mạch',
        image: '/public/images/img1.png',
        rating: 4,
        price: 100000,
        saleOff: 0.15,
        status: 'SELLING',
        type: 'SMALL',
        des: 'Đây là mô tả của sản phẩm này',
        category: 'Hạt',
        createdAt: new Date(2023, 9, 10)
    },
    {
        id: 2,
        name: 'Hạt hạnh nhân bổ sung canxi',
        image: '/public/images/img2.png',
        rating: 5,
        price: 58000,
        saleOff: 0,
        status: 'SELLING',
        type: 'MIDDLE',
        des: 'Đây là mô tả của sản phẩm này',
        category: 'Hạt',
        createdAt: new Date()
    },
    {
        id: 3,
        name: 'Hộp quà chưng tết, có bia, rượu, bánh kẹo',
        image: '/public/images/img3.png',
        rating: 3,
        price: 400000,
        saleOff: 0.1,
        status: 'SELLING',
        type: 'LARGE',
        des: 'Đây là mô tả của sản phẩm này',
        category: 'Rượu',
        createdAt: new Date()
    },
    {
        id: 4,
        name: 'Đậu hà lan, hũ 150g',
        image: '/public/images/img4.png',
        rating: 1,
        price: 300000,
        saleOff: 0.05,
        status: 'SELLING',
        type: 'SMALL',
        des: 'Đây là mô tả của sản phẩm này',
        category: 'Hạt',
        createdAt: new Date()
    },
    {
        id: 5,
        name: 'Trà sen hoa hồng kèm túi hương thơm',
        image: '/public/images/img5.png',
        rating: 5,
        price: 250000,
        saleOff: 0,
        status: 'SELLING',
        type: 'SMALL',
        des: 'Đây là mô tả của sản phẩm này',
        category: 'Trà',
        createdAt: new Date()
    },
    {
        id: 6,
        name: 'Mật trà ôliu, kèm mát cha 4g',
        image: '/public/images/img6.png',
        rating: 4,
        price: 150000,
        saleOff: 0,
        status: 'SELLING',
        type: 'MIDDLE',
        des: 'Đây là mô tả của sản phẩm này',
        category: 'Trà',
        createdAt: new Date()
    },
    {
        id: 7,
        name: 'Bột rau má, kết hợp rượu Spanish',
        image: '/public/images/img7.png',
        rating: 5,
        price: 100000,
        saleOff: 0.15,
        status: 'SELLING',
        type: 'MIDDLE',
        des: 'Đây là mô tả của sản phẩm này',
        category: 'Rượu',
        createdAt: new Date()
    },
    {
        id: 8,
        name: 'Nước cốt dâu tằm, chai 500ml',
        image: '/public/images/img8.png',
        rating: 4,
        price: 4700000,
        saleOff: 0.2,
        status: 'SELLING',
        type: 'MIDDLE',
        des: 'Đây là mô tả của sản phẩm này',
        category: 'Nước cốt',
        createdAt: new Date()
    },
    {
        id: 9,
        name: 'Hộp ăn kem',
        image: '/public/images/img4.png',
        rating: 1,
        price: 300000,
        saleOff: 0.05,
        status: 'SELLING',
        type: 'SMALL',
        des: 'Đây là mô tả của sản phẩm này',
        category: 'Hạt',
        createdAt: new Date()
    },
    {
        id: 10,
        name: 'Bột rau má, kết hợp rượu Spanish',
        image: '/public/images/img7.png',
        rating: 5,
        price: 100000,
        saleOff: 0.15,
        status: 'SELLING',
        type: 'MIDDLE',
        des: 'Đây là mô tả của sản phẩm này',
        category: 'Rượu',
        createdAt: new Date()
    },
];

export {
    listGift
}